/*
        function convertDigimonCSV(csvText) {
    // Parse CSV
    const lines = csvText.trim().split('\n');
    const headers = lines[0].split(',').map(h => h.trim());

    // Find where evolution columns start (after "Attribute")
    const evolutionStartIndex = headers.indexOf('Evolutions');

    // Map for stage conversion
    const stageMap = {
        'I': 'In-Training',
        'II': 'In-Training II',
        'III': 'Rookie',
        'IV': 'Champion',
        'V': 'Ultimate',
        'VI': 'Mega',
        'VI+': 'Mega',
        'Baby': 'Baby',
        'In-Training': 'In-Training',
        'Rookie': 'Rookie',
        'Champion': 'Champion',
        'Ultimate': 'Ultimate',
        'Mega': 'Mega'
    };

    const digimonList = [];
    const evolutionsList = [];
    const processedDigimon = new Set();

    // Process each row (skip header)
    for (let i = 1; i < lines.length; i++) {
        const columns = lines[i].split(',').map(col => col.trim());

        // Skip empty rows
        if (!columns[2]) continue;

        const number = columns[0];
        const name = columns[2];
        const stage = stageMap[columns[3]] || columns[3];
        const attribute = columns[4] || 'None';

        // Add digimon to list if not already processed
        if (!processedDigimon.has(name)) {
            digimonList.push({
                name: name,
                stage: stage,
                attribute: attribute,
                number: number
            });
            processedDigimon.add(name);
        }

        // Process evolutions (columns 5 onwards)
        for (let j = evolutionStartIndex; j < columns.length; j++) {
            const evolutionTo = columns[j];
            if (evolutionTo && evolutionTo.trim() !== '') {
                evolutionsList.push({
                    from: name,
                    to: evolutionTo.trim()
                });
            }
        }
    }

    return {
        digimon: digimonList,
        evolutions: evolutionsList
    };
}

// Example usage with your sample data:
const csvData = `Number,Image,Name,Stage,Attribute,Evolutions,,,,,
1,,Kuramon,I,None,Pagumon,Tsumemon,,,,
2,,Choromon,I,None,Caprimon,,,,,
3,,Dodomon,I,None,Wanyamon,Dorimon,,,,
4,,Bubbmon,I,None,Mochimon,Pyocomon,Tanemon,,,
5,,Punimon,I,None,Tunomon,Nyaromon,,,,
6,,Botamon,I,None,Koromon,,,,,
7,,Poyomon,I,None,Pukamon,Tokomon,,,,
8,,Caprimon,II,None,Hagurumon,Kokuwamon,Toy Agumon,Solarmon,,
9,,Koromon,II,None,Agumon,Guilmon,Dracomon,Kotemon,Betamon,Shoutmon
10,,Tanemon,II,None,Funbeemon,Lalamon,Palmon,Mushmon,Floramon,
11,,Tunomon,II,None,Goburimon,V-Mon,Gabumon,Ryudamon,Elecmon,Zubamon
12,,Tsumemon,II,None,Dracumon,Shamamon,Keramon,,,
13,,Tokomon,II,None,Patamon,Coronamon,Terriermon,Armadimon,Lucemon,
14,,Dorimon,II,None,Dorumon,Monodramon,Snow Goburimon,Lopmon,,
15,,Nyaromon,II,None,Lunamon,Kudamon,Plotmon,Hackmon,,
16,,Pagumon,II,None,Impmon,Pico Devimon,Gazimon,Otamamon,,
17,,Pyocomon,II,None,Piyomon,Penmon,Falcomon,Hawkmon,Hyokomon,Muchomon
18,,Pukamon,II,None,Kamemon,Ganimon,Gomamon,Gizamon,Shakomon,
19,,Mochimon,II,None,Tyumon,Tentomon,Wormmon,Gottsumon,,
20,,Wanyamon,II,None,Gaomon,Bakumon,Bearmon,Renamon,,
21,,Agumon,III,Vaccine,Raptordramon,Geo Greymon,Numemon,Greymon,Coredramon (Green),Agumon -Yuki No Kizuna-
22,,Kudamon,III,Vaccine,Airdramon,Reppamon,Angemon,Ginryumon,Wolfmon,Sorcerimon
23,,Gomamon,III,Vaccine,Mojyamon,Ikkakumon,Yukidarumon,Hyougamon,Ice Devimon,
24,,Coronamon,III,Vaccine,Firamon,Meramon,Growmon,Bao Hackmon,Birdramon,Agnimon
25,,Zubamon,III,Vaccine,Musyamon,Buraimon,Tankmon,Zubaeagermon,Ankylomon,Guardromon (Gold)
26,,Solarmon,III,Vaccine,Starmon,Gold Numemon,Meramon,Guardromon (Gold),,
27,,Terriermon,III,Vaccine,Mojyamon,Lekismon,Gawappamon,Gargomon,Rapidmon Armor,
28,,Tentomon,III,Vaccine,Kabuterimon,Sunflowmon,Kuwagamon,Waspmon,Snimon,
29,,Toy Agumon,III,Vaccine,Blimpmon,Revolmon,Raremon,Tankmon,Gargomon,
30,,Bakumon,III,Vaccine,Meramon,Garurumon,Bakemon,Unimon,Kyubimon,
31,,Hyokomon,III,Vaccine,Peckmon,Birdramon,Dinohumon,Buraimon,,
32,,Piyomon,III,Vaccine,Aquilamon,Birdramon,Unimon,Wizarmon,,
33,,Falcomon,III,Vaccine,Peckmon,Ginryumon,Kiwimon,,,
34,,Plotmon,III,Vaccine,Tailmon,Sangloupmon,Dobermon,Ikkakumon,V-Dramon,Drimogemon
35,,Bearmon,III,Vaccine,Gryzmon,Gaogamon,Mojyamon,Leomon,,
36,,Penmon,III,Vaccine,Peckmon,Buraimon,Kiwimon,Aquilamon,,
37,,Monodramon,III,Vaccine,Strikedramon,Raptordramon,Deltamon,Chrysalimon,Cyclomon,
38,,Ryudamon,III,Vaccine,Reppamon,Coelamon,Ginryumon,Greymon,Monochromon,
39,,Lucemon,III,Vaccine,Lucemon: Falldown Mode,,,,,
40,,Elecmon,III,Data,Aegiomon,Seadramon,Unimon,Kuwagamon,Gekomon,
41,,Gaomon,III,Data,Strikedramon,Gaogamon,Leomon,Nanimon,Turuiemon,
42,,Ganimon,III,Data,Gawappamon,Octmon,Shellmon,Raremon,Snimon,Coelamon
43,,Gabumon,III,Data,Garurumon,Ikkakumon,Drimogemon,Kyubimon,Geremon,Gabumon -Yujo No Kizuna-
44,,Kamemon,III,Data,Gawappamon,Octmon,Shellmon,Karatuki Numemon,Dinohumon,Sorcerimon
45,,Kokuwamon,III,Data,Centalmon,Kuwagamon,Clockmon,Waspmon,Mechanorimon,
46,,Gottsumon,III,Data,Starmon,Guardromon,Golemon,Monochromon,Icemon,Tuchidarumon
47,,Kotemon,III,Data,Turuiemon,Musyamon,Revolmon,Dinohumon,Coredramon (Blue),
48,,Shoutmon,III,Data,Omega Shoutmon,Zubaeagermon,Gargomon,Guardromon (Gold),,
49,,Dracomon,III,Data,Coredramon (Green),Coredramon (Blue),Deltamon,V-Dramon,Seadramon,Tyranomon
50,,Dorumon,III,Data,Raptordramon,Airdramon,Sangloupmon,Xv-Mon,Drimogemon,Dorugamon
51,,Patamon,III,Data,Angemon,Pegasmon,Unimon,Centalmon,,
52,,Hackmon,III,Data,Tailmon,Geo Greymon,Growmon,Bao Hackmon,Greymon,
53,,Palmon,III,Data,Mojyamon,Vegimon,Togemon,Woodmon,Chrysalimon,Platinum Scumon
54,,Floramon,III,Data,Vegimon,Togemon,Woodmon,Sunflowmon,Kiwimon,
55,,Muchomon,III,Data,Airdramon,Peckmon,Birdramon,Fugamon,,
56,,Lalamon,III,Data,Sunflowmon,Togemon,Revolmon,Tuchidarumon,Turuiemon,
57,,Lunamon,III,Data,Lekismon,Garurumon,Yukidarumon,Hyougamon,Sorcerimon,Icemon
58,,Renamon,III,Data,Lekismon,Sunflowmon,Reppamon,Kyubimon,,
59,,Lopmon,III,Data,Gryzmon,Minotaurmon,Leomon,Turuiemon,Wendimon,Tuchidarumon
60,,Impmon,III,Virus,Bakemon,Wizarmon,Clockmon,Sangloupmon,Devimon,Witchmon
61,,Otamamon,III,Virus,Seadramon,Numemon,Gekomon,Karatuki Numemon,Platinum Scumon,
62,,Gazimon,III,Virus,Sangloupmon,Black Tailmon,Gaogamon,Bao Hackmon,Dobermon,Dorugamon
63,,Gizamon,III,Virus,Cyclomon,Flymon,Zubaeagermon,Ankylomon,Geremon,Ranamon
64,,Guilmon,III,Virus,Geo Greymon,Growmon,Xv-Mon,Tyranomon,,
65,,Goburimon,III,Virus,Golemon,Wendimon,Deltamon,Tuskmon,Orgemon,
66,,Shamamon,III,Virus,Minotaurmon,Musyamon,Fugamon,Witchmon,,
67,,Shakomon,III,Virus,Coelamon,Shellmon,Karatuki Numemon,Octmon,Raremon,
68,,Snow Goburimon,III,Virus,Tailmon,Monochromon,Yukidarumon,Hyougamon,Ice Devimon,Icemon
69,,Tyumon,III,Virus,Black Tailmon,Scumon,Tailmon,Gekomon,Geremon,Platinum Scumon
70,,Dracumon,III,Virus,Sangloupmon,Scumon,Wizarmon,Starmon,,
71,,Hagurumon,III,Virus,Clockmon,Mechanorimon,Tankmon,Guardromon,Blimpmon,
72,,Pico Devimon,III,Virus,Bakemon,Ice Devimon,Devimon,Orgemon,,
73,,Funbeemon,III,Virus,Waspmon,Flymon,Dokugumon,Stingmon,Gold Numemon,Kabuterimon
74,,Betamon,III,Virus,Seadramon,Coelamon,Devimon,Numemon,Vegimon,Tuskmon
75,,Mushmon,III,Virus,Scumon,Nanimon,Woodmon,Flymon,,
76,,Armadimon,III,Free,Digmon,Submarimon,Golemon,Ankylomon,,
77,,V-Mon,III,Free,Xv-Mon,V-Dramon,Lighdramon,Magnamon,Fladramon,
78,,Hawkmon,III,Free,Firamon,Holsmon,Shurimon,Aquilamon,,
79,,Wormmon,III,Free,Stingmon,Dokugumon,Snimon,,,
80,,Keramon,III,Unknown,Dokugumon,Wendimon,Octmon,Mechanorimon,Chrysalimon,
81,,Aegiomon,IV,Vaccine,Aegiochusmon,Aegiochusmon: Dark,Aegiochusmon: Holy,Aegiochusmon: Blue,Aegiochusmon: Green,
82,,Ikkakumon,IV,Vaccine,Whamon,Mega Seadramon,Zudomon,Skullseadramon,,
83,,Airdramon,IV,Vaccine,Hisyaryumon,Megadramon,Aero V-Dramon,Gigadramon,,
84,,Angemon,IV,Vaccine,Hippogriffomon,Holy Angemon,Sirenmon,Shakkoumon,,
85,,Kabuterimon,IV,Vaccine,Lilamon,Atlur Kabuterimon,Cannonbeemon,Chimairamon,,
86,,Gargomon,IV,Vaccine,Catch Mamemon,Mach Gaogamon,Rapidmon Perfect,,,
87,,Garurumon,IV,Vaccine,Were Garurumon,Blue Meramon,Taomon,Chimairamon,,
88,,Ginryumon,IV,Vaccine,Hisyaryumon,Skull Greymon,Butenmon,,,
89,,Gryzmon,IV,Vaccine,Were Garurumon,Grappu Leomon,Great Gryzmon,,,
90,,Greymon,IV,Vaccine,Metal Greymon,Megadramon,Skull Greymon,Chimairamon,,
91,,Coredramon (Blue),IV,Vaccine,Wingdramon,Aero V-Dramon,Gigadramon,,,
92,,Geo Greymon,IV,Vaccine,Rize Greymon,Metal Tyranomon,Cyberdramon,,,
93,,Strikedramon,IV,Vaccine,Cyberdramon,Savior Hackmon,Locomon,,,
94,,Snimon,IV,Vaccine,Okuwamon,Fantomon,Archnemon,Jewelbeemon,,
95,,Zubaeagermon,IV,Vaccine,Grademon,Megalo Growmon,Duramon,Knightmon,,
96,,Sorcerimon,IV,Vaccine,Holy Angemon,Piccolomon,Wisemon,,,
97,,Tailmon,IV,Vaccine,Nefertimon,Angewomon,Silphymon,,,
98,,Dobermon,IV,Vaccine,Matadrmon,Dark Super Starmon,Cerberumon,Mummymon,,
99,,Birdramon,IV,Vaccine,Flaremon,Garudamon,Death Meramon,Parrotmon,,
100,,Firamon,IV,Vaccine,Flaremon,Savior Hackmon,Mistymon,,,
101,,V-Dramon,IV,Vaccine,Wingdramon,Aero V-Dramon,Cyberdramon,,,
102,,Buraimon,IV,Vaccine,Butenmon,Duramon,Garudamon,,,
103,,Peckmon,IV,Vaccine,Tyilinmon,Vamdemon,Yatagaramon,,,
104,,Mojyamon,IV,Vaccine,Zudomon,Piccolomon,Mistymon,Mammon,,
105,,Yukidarumon,IV,Vaccine,Crescemon,Angewomon,Panjyamon,Insekimon,Mammon,
106,,Unimon,IV,Vaccine,Hippogriffomon,Holy Angemon,Tyilinmon,,,
107,,Raptordramon,IV,Vaccine,Grademon,Gigadramon,Tankdramon,,,
108,,Revolmon,IV,Vaccine,Pandamon,Super Starmon,Wisemon,,,
109,,Leomon,IV,Vaccine,Flaremon,Grappu Leomon,Panjyamon,Loader Leomon,,
110,,Reppamon,IV,Vaccine,Tyilinmon,Mega Seadramon,Angewomon,Doruguremon,,
111,,Icemon,IV,Data,Crescemon,Insekimon,Panjyamon,,,
112,,Wizarmon,IV,Data,Nanomon,Mistymon,Wisemon,,,
113,,Witchmon,IV,Data,Lady Devimon,Angewomon,Lilimon,,,
114,,Gaogamon,IV,Data,Mach Gaogamon,Savior Hackmon,Dark Super Starmon,,,
115,,Gawappamon,IV,Data,Shawujinmon,Hangyomon,Tonosama Gekomon,,,
116,,Kiwimon,IV,Data,Lilamon,Sirenmon,Delumon,Jyureimon,,
117,,Kyubimon,IV,Data,Blue Meramon,Cerberumon,Taomon,Enbarrmon,,
118,,Clockmon,IV,Data,Ex-Tyranomon,Andromon,Zudomon,Knightmon,,
119,,Centalmon,IV,Data,Andromon,Nanomon,Rapidmon Perfect,,,
120,,Sunflowmon,IV,Data,Lilamon,Lilimon,Delumon,Pumpmon,,
121,,Seadramon,IV,Data,Whamon,Mega Seadramon,Waru Seadramon,Hisyaryumon,Sharkmon,Skullseadramon
122,,Coelamon,IV,Data,Waru Seadramon,Metal Tyranomon,Anomalocarimon,Hangyomon,Skullseadramon,
123,,Shellmon,IV,Data,Whamon,Piccolomon,Anomalocarimon,,,
124,,Starmon,IV,Data,Volcamon,Super Starmon,Dark Super Starmon,Mamemon,,
125,,Tankmon,IV,Data,Big Mamemon,Locomon,Tankdramon,,,
126,,Tuchidarumon,IV,Data,Delumon,Gerbemon,Andiramon,,,
127,,Dinohumon,IV,Data,Shawujinmon,Grademon,Knightmon,,,
128,,Tyranomon,IV,Data,Ex-Tyranomon,Groundramon,Metal Greymon,Metal Tyranomon,,
129,,Turuiemon,IV,Data,Matadrmon,Mach Gaogamon,Andiramon,,,
130,,Togemon,IV,Data,Lilimon,Jyureimon,Pumpmon,,,
131,,Drimogemon,IV,Data,Triceramon,Loader Leomon,Brachiomon,,,
132,,Dorugamon,IV,Data,Rize Greymon,Doruguremon,Great Gryzmon,,,
133,,Bao Hackmon,IV,Data,Rize Greymon,Savior Hackmon,Loader Leomon,,,
134,,Blimpmon,IV,Data,Locomon,Metal Mamemon,Master Blimpmon,,,
135,,Meramon,IV,Data,Big Mamemon,Blue Meramon,Death Meramon,,,
136,,Monochromon,IV,Data,Triceramon,Cerberumon,Mammon,,,
137,,Lekismon,IV,Data,Crescemon,Were Garurumon,Grappu Leomon,,,
138,,Ice Devimon,IV,Virus,Crescemon,Lady Devimon,Panjyamon,Enbarrmon,,
139,,Wendimon,IV,Virus,Archnemon,Death Meramon,Andiramon,,,
140,,Woodmon,IV,Virus,Jyureimon,Taomon,Pumpmon,,,
141,,Orgemon,IV,Virus,Skull Satamon,Mummymon,Digitamamon,,,
142,,Octmon,IV,Virus,Dagomon,Digitamamon,Hangyomon,,,
143,,Guardromon,IV,Virus,Catch Mamemon,Locomon,Andromon,,,
144,,Karatuki Numemon,IV,Virus,Orochimon,Waru Seadramon,Black King Numemon,Pandamon,,
145,,Growmon,IV,Virus,Megalo Growmon,Groundramon,Doruguremon,,,
146,,Kuwagamon,IV,Virus,Jyureimon,Okuwamon,Anomalocarimon,Chimairamon,,
147,,Gekomon,IV,Virus,Sirenmon,Tonosama Gekomon,Hangyomon,,,
148,,Geremon,IV,Virus,Catch Mamemon,Super Starmon,Monzaemon,,,
149,,Coredramon (Green),IV,Virus,Megalo Growmon,Groundramon,Skull Greymon,,,
150,,Gold Numemon,IV,Virus,Waru Seadramon,Vademon,Black King Numemon,,,
151,,Golemon,IV,Virus,Volcamon,Mammon,Insekimon,,,
152,,Cyclomon,IV,Virus,Grademon,Cyberdramon,Brachiomon,,,
153,,Sangloupmon,IV,Virus,Matadrmon,Vamdemon,Astamon,,,
154,,Scumon,IV,Virus,Monzaemon,Etemon,Gerbemon,Mamemon,,
155,,Tuskmon,IV,Virus,Triceramon,Groundramon,Digitamamon,,,
156,,Devimon,IV,Virus,Vamdemon,Lady Devimon,Infermon,Skull Satamon,Astamon,
157,,Deltamon,IV,Virus,Orochimon,Chimairamon,Skull Baluchimon,Metal Greymon,Sharkmon,
158,,Dokugumon,IV,Virus,Archnemon,Mummymon,Atlur Kabuterimon,Infermon,,
159,,Nanimon,IV,Virus,Volcamon,Super Starmon,Etemon,Mamemon,,
160,,Numemon,IV,Virus,Monzaemon,Dark Super Starmon,Etemon,,,
161,,Bakemon,IV,Virus,Vamdemon,Blue Meramon,Fantomon,Enbarrmon,,
162,,Hyougamon,IV,Virus,Zudomon,Fantomon,Panjyamon,,,
163,,Fugamon,IV,Virus,Volcamon,Skull Satamon,Garudamon,,,
164,,Flymon,IV,Virus,Megadramon,Atlur Kabuterimon,Okuwamon,Jewelbeemon,,
165,,Platinum Scumon,IV,Virus,Vademon,Mamemon,Metal Mamemon,,,
166,,Black Tailmon,IV,Virus,Pandamon,Lady Devimon,Skull Baluchimon,,,
167,,Vegimon,IV,Virus,Tonosama Gekomon,Gerbemon,Vademon,,,
168,,Minotaurmon,IV,Virus,Triceramon,Etemon,Grappu Leomon,,,
169,,Musyamon,IV,Virus,Grademon,Butenmon,Hisyaryumon,,,
170,,Mechanorimon,IV,Virus,Big Mamemon,Megadramon,Nanomon,,,
171,,Raremon,IV,Virus,Dagomon,Black King Numemon,Tonosama Gekomon,Ex-Tyranomon,Skull Baluchimon,
172,,Waspmon,IV,Virus,Rapidmon Perfect,Cannonbeemon,Tankdramon,,,
173,,Aquilamon,IV,Free,Garudamon,Parrotmon,Silphymon,Yatagaramon,,
174,,Ankylomon,IV,Free,Shakkoumon,Insekimon,Brachiomon,,,
175,,Xv-Mon,IV,Free,Dinobeemon,Rize Greymon,Paildramon,,,
176,,Guardromon (Gold),IV,Free,Duramon,Cannonbeemon,Master Blimpmon,,,
177,,Stingmon,IV,Free,Okuwamon,Jewelbeemon,Dinobeemon,Paildramon,,
178,,Chrysalimon,IV,Unknown,Dagomon,Orochimon,Archnemon,Infermon,,
179,,Submarimon,Armor,Free,,,,,,
180,,Shurimon,Armor,Free,,,,,,
181,,Digmon,Armor,Free,,,,,,
182,,Nefertimon,Armor,Free,,,,,,
183,,Fladramon,Armor,Free,,,,,,
184,,Pegasmon,Armor,Free,,,,,,
185,,Holsmon,Armor,Free,,,,,,
186,,Lighdramon,Armor,Free,,,,,,
187,,Agnimon,Human Hybrid,Variable,Aldamon,Vritramon,,,,
188,,Wolfmon,Human Hybrid,Variable,Beowolfmon,Garummon,,,,
189,,Ranamon,Human Hybrid,Variable,Calamaramon,,,,,
190,,Vritramon,Beast Hybrid,Variable,Aldamon,Agnimon,,,,
191,,Calamaramon,Beast Hybrid,Variable,Ranamon,,,,,
192,,Garummon,Beast Hybrid,Variable,Beowolfmon,Wolfmon,,,,
193,,Aegiochusmon,V,Vaccine,Jupitermon,,,,,
194,,Aegiochusmon: Green,V,Vaccine,Jupitermon,,,,,
195,,Aegiochusmon: Dark,V,Vaccine,Chronomon Destroy,,,,,
196,,Aegiochusmon: Blue,V,Vaccine,Jupitermon,,,,,
197,,Aegiochusmon: Holy,V,Vaccine,Jupitermon,,,,,
198,,Atlur Kabuterimon,V,Vaccine,Tyrant Kabuterimon,Herakle Kabuterimon,,,,
199,,Andromon,V,Vaccine,Hi Andromon,Boltmon,Craniummon,,,
200,,Wingdramon,V,Vaccine,Shine Greymon,Valdurmon,Slayerdramon,,,
201,,Aero V-Dramon,V,Vaccine,Goddramon,Slayerdramon,Ulforce V-Dramon,,,
202,,Ex-Tyranomon,V,Vaccine,Rust Tyranomon,Belphemon: Sleep Mode,Cherubimon (Virtue),,,
203,,Angewomon,V,Vaccine,Junomon,Ofanimon,Holydramon,Mastemon,,
204,,Garudamon,V,Vaccine,Griffomon,Hououmon,Jesmon,,,
205,,Grappu Leomon,V,Vaccine,Bancho Leomon,Marsmon,Saber Leomon,Duftmon,,
206,,Grademon,V,Vaccine,Alphamon,Durandamon,Dynasmon,,,
207,,Great Gryzmon,V,Vaccine,Callismon,Cherubimon (Vice),,,,
208,,Cerberumon,V,Vaccine,Plutomon,Cerberumon: Werewolf Mode,Saber Leomon,,,
209,,Cerberumon: Werewolf Mode,V,Vaccine,Plutomon,Cerberumon,Saber Leomon,,,
210,,Cyberdramon,V,Vaccine,Ulforce V-Dramon,Justimon,,,,
211,,Jewelbeemon,V,Vaccine,Herakle Kabuterimon,Tiger Vespamon,,,,
212,,Zudomon,V,Vaccine,Vikemon,Plesiomon,,,,
213,,Tyilinmon,V,Vaccine,Sleipmon,Crossmon,Valkyrimon,,,
214,,Duramon,V,Vaccine,War Greymon,Dukemon,Durandamon,,,
215,,Parrotmon,V,Vaccine,Crossmon,Hououmon,,,,
216,,Panjyamon,V,Vaccine,Mirage Gaogamon,Saber Leomon,,,,
217,,Hisyaryumon,V,Vaccine,Ouryumon,Gaioumon,,,,
218,,Butenmon,V,Vaccine,Chronomon,Chronomon Destroy,Griffomon,Gaioumon,,
219,,Flaremon,V,Vaccine,Apollomon,Seraphimon,,,,
220,,Whamon,V,Vaccine,Leviamon,Neptunemon,Plesiomon,Marin Angemon,,
221,,Holy Angemon,V,Vaccine,Goddramon,Seraphimon,Clavis Angemon,Slash Angemon,,
222,,Mammon,V,Vaccine,Vikemon,Skull Mammon,,,,
223,,Metal Greymon,V,Vaccine,War Greymon,Gaioumon,,,,
224,,Monzaemon,V,Vaccine,King Etemon,Callismon,,,,
225,,Yatagaramon,V,Vaccine,Valdurmon,Ravmon,Kuzuhamon,,,
226,,Rize Greymon,V,Vaccine,Sleipmon,Shine Greymon,Magna Kidmon,,,
227,,Rapidmon Perfect,V,Vaccine,Saint Galgomon,Hi Andromon,,,,
228,,Loader Leomon,V,Vaccine,Bancho Leomon,Metal Garurumon,Chaosdramon,,,
229,,Were Garurumon,V,Vaccine,Mercurymon,Metal Garurumon,,,,
230,,Anomalocarimon,V,Data,Vulcanusmon,Pukumon,,,,
231,,Enbarrmon,V,Data,Sleipmon,Skull Mammon,Enbarrmon Craniummon,,,
232,,Andiramon,V,Data,Dianamon,Cherubimon (Virtue),Cherubimon (Vice),,,
233,,Insekimon,V,Data,Metal Etemon,Boltmon,,,,
234,,Omega Shoutmon,V,Data,Pile Volcamon,Magna Kidmon,Durandamon,,,
235,,Chimairamon,V,Data,Grand Dracumon,Millenniumon,Mugendramon,,,
236,,Catch Mamemon,V,Data,Platinum Numemon,Prince Mamemon,,,,
237,,Crescemon,V,Data,Dianamon,Cherubimon (Virtue),Lord Knightmon,,,
238,,Super Starmon,V,Data,Goddramon,Prince Mamemon,Justimon,,,
239,,Skull Baluchimon,V,Data,Skull Mammon,Skull Baluchimon Titamon,,,,
240,,Savior Hackmon,V,Data,Gankoomon,Tiger Vespamon,Jesmon,,,
241,,Sirenmon,V,Data,Marin Angemon,Ceresmon,,,,
242,,Taomon,V,Data,Venusmon,Sakuyamon,Kuzuhamon,,,
243,,Digitamamon,V,Data,Bacchusmon,Titamon,,,,
244,,Death Meramon,V,Data,Beelzebumon,Boltmon,Avenge Kidmon,,,
245,,Delumon,V,Data,Valdurmon,Ceresmon,Platinum Numemon,,,
246,,Triceramon,V,Data,Breakdramon,Ultimate Brachiomon,,,,
247,,Doruguremon,V,Data,Dorugoramon,Alphamon,,,,
248,,Knightmon,V,Data,Zanbamon,Slash Angemon,Lord Knightmon,Duftmon,,
249,,Hangyomon,V,Data,Neptunemon,Plesiomon,,,,
250,,Pandamon,V,Data,Mercurymon,Mirage Gaogamon,Justimon,,,
251,,Pumpmon,V,Data,Rosemon,Lotusmon,,,,
252,,Big Mamemon,V,Data,Platinum Numemon,Prince Mamemon,Grand Locomon,,,
253,,Piccolomon,V,Data,Venusmon,Ofanimon,Clavis Angemon,,,
254,,Hippogriffomon,V,Data,Griffomon,Crossmon,Dynasmon,,,
255,,Brachiomon,V,Data,Ouryumon,Rust Tyranomon,Ultimate Brachiomon,,,
256,,Volcamon,V,Data,Bancho Leomon,Pile Volcamon,Gankoomon,Apollomon,,
257,,Master Blimpmon,V,Data,Grand Locomon,Gundramon,,,,
258,,Mach Gaogamon,V,Data,Mirage Gaogamon,Saint Galgomon,,,,
259,,Mamemon,V,Data,Pukumon,Prince Mamemon,,,,
260,,Mega Seadramon,V,Data,Jumbo Gamemon,Ouryumon,Metal Seadramon,,,
261,,Metal Mamemon,V,Data,Metal Garurumon,Magna Kidmon,,,,
262,,Lilamon,V,Data,Lilithmon,Rosemon,Pinochimon,,,
263,,Lilimon,V,Data,Rosemon,Ceresmon,,,,
264,,Locomon,V,Data,Grand Locomon,Hi Andromon,,,,
265,,Astamon,V,Virus,Beelzebumon,Plutomon,Belphemon: Sleep Mode,Venom Vamdemon,,
266,,Archnemon,V,Virus,Lilithmon,Tyrant Kabuterimon,Lotusmon,,,
267,,Vamdemon,V,Virus,Demon,Belial Vamdemon,Venom Vamdemon,,,
268,,Etemon,V,Virus,Pile Volcamon,King Etemon,Metal Etemon,,,
269,,Okuwamon,V,Virus,Tyrant Kabuterimon,Herakle Kabuterimon,Gran Kuwagamon,,,
270,,Orochimon,V,Virus,Bacchusmon,Gundramon,Minervamon,,,
271,,Gerbemon,V,Virus,Jumbo Gamemon,Metal Etemon,,,,
272,,Gigadramon,V,Virus,Gundramon,Chaosdramon,,,,
273,,Cannonbeemon,V,Virus,Saint Galgomon,Tiger Vespamon,,,,
274,,Groundramon,V,Virus,Megidramon,Breakdramon,,,,
275,,Sharkmon,V,Virus,Neptunemon,Metal Seadramon,,,,
276,,Shawujinmon,V,Virus,Barbamon,Jumbo Gamemon,Pinochimon,,,
277,,Jyureimon,V,Virus,Pinochimon,Rosemon,Gran Kuwagamon,,,
278,,Skull Greymon,V,Virus,Titamon,Skull Mammon,,,,
279,,Skull Satamon,V,Virus,Barbamon,Piemon,Ebemon,,,
280,,Skullseadramon,V,Virus,Leviamon,Metal Seadramon,,,,
281,,Dark Super Starmon,V,Virus,Beel Starmon,Titamon,Ravmon,,,
282,,Dagomon,V,Virus,Vulcanusmon,Ebemon,,,,
283,,Tankdramon,V,Virus,Gundramon,Darkdramon,,,,
284,,Tonosama Gekomon,V,Virus,King Etemon,Bacchusmon,Pukumon,,,
285,,Nanomon,V,Virus,Pharaohmon,Diablomon,,,,
286,,Fantomon,V,Virus,Sakuyamon,Piemon,Belphemon: Sleep Mode,Ravmon,,
287,,Black King Numemon,V,Virus,Platinum Numemon,Metal Etemon,,,,
288,,Blue Meramon,V,Virus,Marsmon,Pharaohmon,,,,
289,,Vademon,V,Virus,Ebemon,Avenge Kidmon,,,,
290,,Matadrmon,V,Virus,Grand Dracumon,Slash Angemon,Kuzuhamon,,,
291,,Mummymon,V,Virus,Pharaohmon,Hi Andromon,Avenge Kidmon,,,
292,,Mistymon,V,Virus,Chaos Dukemon,Zanbamon,Medieval Dukemon,Dynasmon,,
293,,Megadramon,V,Virus,Megidramon,Mugendramon,,,,
294,,Megalo Growmon,V,Virus,Megidramon,Dukemon,Chaos Dukemon,Chaosdramon,,
295,,Metal Tyranomon,V,Virus,Rust Tyranomon,Mugendramon,Ultimate Brachiomon,,,
296,,Lucemon: Falldown Mode,V,Virus,Lucemon: Satan Mode,,,,,
297,,Lady Devimon,V,Virus,Lilithmon,Beel Starmon,Mastemon,,,
298,,Wisemon,V,Virus,Demon,Chaos Dukemon,Ancient Wisemon,,,
299,,Waru Seadramon,V,Virus,Leviamon,Megidramon,Metal Seadramon,,,
300,,Shakkoumon,V,Free,Goddramon,Junomon,Vikemon,Holydramon,,
301,,Silphymon,V,Free,Beel Starmon,Minervamon,Valkyrimon,,,
302,,Dinobeemon,V,Free,Gran Kuwagamon,Tiger Vespamon,,,,
303,,Paildramon,V,Free,Dorugoramon,Imperialdramon: Dragon Mode,Darkdramon,,,
304,,Infermon,V,Unknown,Belial Vamdemon,Diablomon,Cherubimon (Vice),,,
305,,Aldamon,Fusion Hybrid,Variable,Kaiser Greymon,,,,,
306,,Beowolfmon,Fusion Hybrid,Variable,Magna Garurumon,,,,,
307,,Apollomon,VI,Vaccine,Grace Novamon,,,,,
308,,Alphamon,VI,Vaccine,Alphamon: Ouryuken,,,,,
309,,Ulforce V-Dramon,VI,Vaccine,,,,,,
310,,Valdurmon,VI,Vaccine,Chaosmon: Valdur Arm,,,,,
311,,Venusmon,VI,Vaccine,,,,,,
312,,War Greymon,VI,Vaccine,Omegamon,,,,,
313,,Ouryumon,VI,Vaccine,Alphamon: Ouryuken,,,,,
314,,Ofanimon,VI,Vaccine,,,,,,
315,,Clavis Angemon,VI,Vaccine,,,,,,
316,,Craniummon,VI,Vaccine,Enbarrmon Craniummon,,,,,
317,,Crossmon,VI,Vaccine,,,,,,
318,,Chronomon,VI,Vaccine,,,,,,
319,,Cherubimon (Vice),VI,Vaccine,,,,,,
320,,Cherubimon (Virtue),VI,Vaccine,,,,,,
321,,Goddramon,VI,Vaccine,,,,,,
322,,Shine Greymon,VI,Vaccine,Shine Greymon: Burst Mode,,,,,
323,,Justimon,VI,Vaccine,,,,,,
324,,Skull Mammon,VI,Vaccine,,,,,,
325,,Slash Angemon,VI,Vaccine,,,,,,
326,,Sleipmon,VI,Vaccine,,,,,,
327,,Slayerdramon,VI,Vaccine,Examon,,,,,
328,,Seraphimon,VI,Vaccine,,,,,,
329,,Saint Galgomon,VI,Vaccine,,,,,,
330,,Durandamon,VI,Vaccine,,,,,,
331,,Neptunemon,VI,Vaccine,,,,,,
332,,Hi Andromon,VI,Vaccine,,,,,,
333,,Bancho Leomon,VI,Vaccine,Chaosmon: Valdur Arm,Chaosmon,,,,
334,,Herakle Kabuterimon,VI,Vaccine,,,,,,
335,,Hououmon,VI,Vaccine,,,,,,
336,,Holydramon,VI,Vaccine,,,,,,
337,,Mastemon,VI,Vaccine,,,,,,
338,,Marin Angemon,VI,Vaccine,,,,,,
339,,Marsmon,VI,Vaccine,,,,,,
340,,Jupitermon,VI,Vaccine,Jupitermon: Wrath Mode,,,,,
341,,Ravmon,VI,Vaccine,Ravmon: Burst Mode,,,,,
342,,Ultimate Brachiomon,VI,Data,,,,,,
343,,Vulcanusmon,VI,Data,,,,,,
344,,Gankoomon,VI,Data,,,,,,
345,,Kuzuhamon,VI,Data,,,,,,
346,,Grand Locomon,VI,Data,,,,,,
347,,Griffomon,VI,Data,,,,,,
348,,Ceresmon,VI,Data,Ceresmon Medium,,,,,
349,,Ceresmon Medium,VI,Data,Ceresmon,,,,,
350,,Saber Leomon,VI,Data,,,,,,
351,,Sakuyamon,VI,Data,,,,,,
352,,Jesmon,VI,Data,,,,,,
353,,Jumbo Gamemon,VI,Data,,,,,,
354,,Dianamon,VI,Data,Grace Novamon,,,,,
355,,Dynasmon,VI,Data,,,,,,
356,,Duftmon,VI,Data,Duftmon: Leopard Mode,,,,,
357,,Duftmon: Leopard Mode,VI,Data,Duftmon,,,,,
358,,Dorugoramon,VI,Data,,,,,,
359,,Pile Volcamon,VI,Data,,,,,,
360,,Prince Mamemon,VI,Data,,,,,,
361,,Plesiomon,VI,Data,,,,,,
362,,Boltmon,VI,Data,,,,,,
363,,Mirage Gaogamon,VI,Data,Mirage Gaogamon: Burst Mode,,,,,
364,,Metal Garurumon,VI,Data,Omegamon,,,,,
365,,Metal Seadramon,VI,Data,,,,,,
366,,Medieval Dukemon,VI,Data,,,,,,
367,,Rosemon,VI,Data,Rosemon: Burst Mode,,,,,
368,,Lotusmon,VI,Data,,,,,,
369,,Avenge Kidmon,VI,Virus,,,,,,
370,,Ebemon,VI,Virus,,,,,,
371,,Venom Vamdemon,VI,Virus,,,,,,
372,,Ancient Wisemon,VI,Virus,,,,,,
373,,Gaioumon,VI,Virus,,,,,,
374,,Chaos Dukemon,VI,Virus,,,,,,
375,,Chaosdramon,VI,Virus,,,,,,
376,,Callismon,VI,Virus,,,,,,
377,,Gundramon,VI,Virus,,,,,,
378,,King Etemon,VI,Virus,,,,,,
379,,Grand Dracumon,VI,Virus,,,,,,
380,,Chronomon Destroy,VI,Virus,,,,,,
381,,Zanbamon,VI,Virus,,,,,,
382,,Undead Plutomon,VI,Virus,,,,,,
383,,Darkdramon,VI,Virus,Chaosmon,,,,,
384,,Tiger Vespamon,VI,Virus,,,,,,
385,,Titamon,VI,Virus,Skull Baluchimon Titamon,,,,,
386,,Tyrant Kabuterimon,VI,Virus,,,,,,
387,,Demon,VI,Virus,,,,,,
388,,Dukemon,VI,Virus,Dukemon: Crimson Mode,,,,,
389,,Bacchusmon,VI,Virus,Bacchusmon Drunk,,,,,
390,,Bacchusmon Drunk,VI,Virus,Bacchusmon,,,,,
391,,Barbamon,VI,Virus,,,,,,
392,,Piemon,VI,Virus,Apocalymon,,,,,
393,,Pinochimon,VI,Virus,,,,,,
394,,Pharaohmon,VI,Virus,,,,,,
395,,Pukumon,VI,Virus,,,,,,
396,,Platinum Numemon,VI,Virus,,,,,,
397,,Plutomon,VI,Virus,Undead Plutomon,,,,,
398,,Breakdramon,VI,Virus,Examon,,,,,
399,,Belial Vamdemon,VI,Virus,,,,,,
400,,Beel Starmon,VI,Virus,,,,,,
401,,Beelzebumon,VI,Virus,Beelzebumon: Blast Mode,,,,,
402,,Belphemon: Sleep Mode,VI,Virus,Belphemon: Rage Mode,,,,,
403,,Magna Kidmon,VI,Virus,,,,,,
404,,Minervamon,VI,Virus,Mervamon,,,,,
405,,Millenniumon,VI,Virus,,,,,,
406,,Mugendramon,VI,Virus,Millenniumon,,,,,
407,,Megidramon,VI,Virus,,,,,,
408,,Metal Etemon,VI,Virus,,,,,,
409,,Mercurymon,VI,Virus,,,,,,
410,,Junomon,VI,Virus,Junomon: Hysteric Mode,,,,,
411,,Junomon: Hysteric Mode,VI,Virus,Junomon,,,,,
412,,Rust Tyranomon,VI,Virus,,,,,,
413,,Leviamon,VI,Virus,,,,,,
414,,Lilithmon,VI,Virus,,,,,,
415,,Lord Knightmon,VI,Virus,,,,,,
416,,Imperialdramon: Dragon Mode,VI,Free,Imperialdramon: Fighter Mode,Imperialdramon: Paladin Mode,,,,
417,,Imperialdramon: Fighter Mode,VI,Free,Imperialdramon: Paladin Mode,Imperialdramon: Dragon Mode,,,,
418,,Vikemon,VI,Free,,,,,,
419,,Valkyrimon,VI,Free,,,,,,
420,,Gran Kuwagamon,VI,Free,,,,,,
421,,Diablomon,VI,Unknown,Armagemon,,,,,
422,,Rapidmon Armor,Golden Armor,Vaccine,,,,,,
423,,Magnamon,Golden Armor,Free,,,,,,
424,,Kaiser Greymon,Transcendent Hybrid,Variable,Susanoomon,,,,,
425,,Magna Garurumon,Transcendent Hybrid,Variable,Susanoomon,Magna Garurumon: Separation,,,,
426,,Magna Garurumon: Separation,Transcendent Hybrid,Variable,Magna Garurumon,,,,,
427,,Alphamon: Ouryuken,VI+,Vaccine,,,,,,
428,,Enbarrmon Craniummon,VI+,Vaccine,,,,,,
429,,Imperialdramon: Paladin Mode,VI+,Vaccine,,,,,,
430,,Omegamon,VI+,Vaccine,Omegamon Zwart,,,,,
431,,Omegamon Zwart,VI+,Vaccine,Omegamon,,,,,
432,,Chaosmon,VI+,Vaccine,,,,,,
433,,Chaosmon: Valdur Arm,VI+,Vaccine,,,,,,
434,,Grace Novamon,VI+,Vaccine,,,,,,
435,,Shine Greymon: Burst Mode,VI+,Vaccine,,,,,,
436,,Susanoomon,VI+,Vaccine,,,,,,
437,,Jupitermon: Wrath Mode,VI+,Vaccine,,,,,,
438,,Ravmon: Burst Mode,VI+,Vaccine,,,,,,
439,,Examon,VI+,Data,,,,,,
440,,Mirage Gaogamon: Burst Mode,VI+,Data,,,,,,
441,,Rosemon: Burst Mode,VI+,Data,,,,,,
442,,Skull Baluchimon Titamon,VI+,Virus,,,,,,
443,,Dukemon: Crimson Mode,VI+,Virus,,,,,,
444,,Beelzebumon: Blast Mode,VI+,Virus,,,,,,
445,,Belphemon: Rage Mode,VI+,Virus,,,,,,
446,,Mervamon,VI+,Virus,,,,,,
447,,Lucemon: Satan Mode,VI+,Virus,,,,,,
448,,Armagemon,VI+,Unknown,,,,,,
449,,Agumon -Yuki No Kizuna-,VI+,Unknown,,,,,,
450,,Apocalymon,VI+,Unknown,,,,,,
451,,Gabumon -Yujo No Kizuna-,VI+,Unknown,,,,,,`;

const result = convertDigimonCSV(csvData);

// Output will be:
console.log(result);
         */